# 生产环境配置
llm:
  api:
    # 生产环境必须使用环境变量
    key: ${LLM_API_KEY}
    url: ${LLM_API_URL:https://qianfan.baidubce.com/v2/chat/completions}
    model: ${LLM_MODEL:ernie-speed-pro-128k}
    timeout: 60000

# 生产环境日志配置
logging:
  level:
    com.demo.llmstreaming: INFO
    org.springframework.web: WARN
    okhttp3: WARN
  file:
    name: /var/log/llm-streaming-demo/application.log

